### PR TITLE
Update interactive blogs

### PR DESCRIPTION
**Pull request by metehaansever**
I updated interactive interface's blog with new UI elements. I am open for suggestions. I'll wait until merge the new UI to master branch. :nerd_face:

### CODE REVIEW

**Comment by meren** [comment]
Hi @metehaansever, thank you for these changes. While going through them I realized that you are replacing markdown-formatted content with HTML notation (which defeats the purpose of using markdown). You can easily see the difference by going through the diff output. Here is an example:

image

Can you please follow the existing style?

**Comment by meren** [comment]
There should be no `<br />` tags in the document. I wonder if they are added automatically by your editor. If that is the case please use a MacDown equivalent for your system so everything is in your control :)

**Comment by metehaansever** [comment]
image
I was trying to use page more efficient. That's why i had to use some html elements like `<br/>`. I couldn't do it without `<br/>`, that's why i am discard these changes and make it simplify page.

**Comment by meren** [comment]
I understand :) But it is also OK to include an image that is a single piece and in the middle of the page with a smaller width so people can click on it to see the larger version. Avoiding HTML code in markdown documents as much as possible is the best practice.

**Comment by metehaansever** [comment]
> I understand :) But it is also OK to include an image that is a single piece and in the middle of the page with a smaller width so people can click on it to see the larger version. Avoiding HTML code in markdown documents as much as possible is the best practice.

Thank you for advice Meren, i'll fix it :)

**Pull request closed without merging**
