### PR TITLE
Updated vocabulary for HMMs

### PR DESCRIPTION
**Pull request by thapasz**

### CODE REVIEW

**Comment by meren** [comment]
Dear @thapasz, thank you very much for this!

Although, I'm wondering if you'd consider making this definition more like the other definitions :) I feel that it would be most beneficial to quickly (and very briefly) describe how HMMs are used in microbial 'omics, what are the good for in particular, and how does this approach they compare to other search algorithms. For more theoretical and detailed descriptions of HMMs one can link resources like Wikipedia.

Also, FAQ format is not really fitting well with other definitions. Perhaps it is most helpful to imagine this vocabulary page like a dictionary.

Please let me know if you agree and/or feel free to update your commit.

Thank you very much again!

Best wishes,

**Comment by thapasz** [comment]
Right on!! I agree with you. 

I have updated the definition and taken off the jargon (reduced it significantly). Per your suggestion, I have added how HMMs profiles are used exclusively in-terms of sequence profiling. I attempted to compare with BLAST technique. I have also pointed at two traits that gives HMMs an edge over BLAST. 

I have kept the last paragraph where I show how HMMs can be utilized within Anvi'o and if you think I should drop it, I could make another update to my commit. 

Please, feel free to let me know thoughts/suggestions. 

Thank you very much for your time.

**Comment by meren** [comment]
This is great! I'm now merging this. Please feel free to fill out the sticker form ;)

Thank you very much for your help, @thapasz!

Best wishes,
Meren.

**Comment by thapasz** [comment]
Thank you very much. Thank you for creating such a great platform. Much obliged. 

Best wishes to you as well. 

Sincerely,

**Pull request merged**
